// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MarsProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class LanguageFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Language", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Language.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Language.feature.ndjson", 11);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("01 Verify whether user with valid credentials is redirected to Profile page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("01 Verify whether user with valid credentials is redirected to Profile page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("languageTests")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Hi Lija\"", "0", null, DisplayName="01 Verify whether user with valid credentials is redirected to Profile page(\"lija" +
            "2512@gmail.com\",\"123456\",\"Hi Lija\",0)")]
        public async global::System.Threading.Tasks.Task _01VerifyWhetherUserWithValidCredentialsIsRedirectedToProfilePage(string email_Address, string password, string profile_Name, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "languageTests"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Profile_Name", profile_Name);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01 Verify whether user with valid credentials is redirected to Profile page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 8
 await testRunner.AndAsync(string.Format("the text {0} should be displayed.", profile_Name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("02 Verify whether user with invalid credentials is able to login and access the p" +
            "rofile page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("02 Verify whether user with invalid credentials is able to login and access the p" +
            "rofile page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija@gmail.com\"", "\"1234\"", "1", null, DisplayName="02 Verify whether user with invalid credentials is able to login and access the p" +
            "rofile page(\"lija@gmail.com\",\"1234\",1)")]
        public async global::System.Threading.Tasks.Task _02VerifyWhetherUserWithInvalidCredentialsIsAbleToLoginAndAccessTheProfilePage(string email_Address, string password, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02 Verify whether user with invalid credentials is able to login and access the p" +
                    "rofile page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.WhenAsync(string.Format("the user logs in with invalid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.ThenAsync("the user should not be redirected to the Profile Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("03 Verify whether the user on clicking Add New button under language tab is able " +
            "to create a record")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("03 Verify whether the user on clicking Add New button under language tab is able " +
            "to create a record")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Fluent\"", "\"English\"", "2", null, DisplayName="03 Verify whether the user on clicking Add New button under language tab is able " +
            "to create a record(\"lija2512@gmail.com\",\"123456\",\"Fluent\",\"English\",2)")]
        public async global::System.Threading.Tasks.Task _03VerifyWhetherTheUserOnClickingAddNewButtonUnderLanguageTabIsAbleToCreateARecord(string email_Address, string password, string languagelevel, string language, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Languagelevel", languagelevel);
            argumentsOfScenario.Add("Language", language);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03 Verify whether the user on clicking Add New button under language tab is able " +
                    "to create a record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
 await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language, languagelevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync(string.Format("the {0} record should be displayed in the table", language), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("04 Verify whether the user is able to update the language record created")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("04 Verify whether the user is able to update the language record created")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"English\"", "\"Basic\"", "\"Native/Bilingual\"", "3", null, DisplayName="04 Verify whether the user is able to update the language record created(\"lija251" +
            "2@gmail.com\",\"123456\",\"English\",\"Basic\",\"Native/Bilingual\",3)")]
        public async global::System.Threading.Tasks.Task _04VerifyWhetherTheUserIsAbleToUpdateTheLanguageRecordCreated(string email_Address, string password, string language, string languageLevel, string updatedLanguageLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Language", language);
            argumentsOfScenario.Add("LanguageLevel", languageLevel);
            argumentsOfScenario.Add("UpdatedLanguageLevel", updatedLanguageLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04 Verify whether the user is able to update the language record created", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
 await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language, languageLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync(string.Format("the {0} record should be displayed in the table", language), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.WhenAsync(string.Format("the user clicks on edit icon and updates the field with {0}", updatedLanguageLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
 await testRunner.ThenAsync(string.Format("the {0} of the record should get updated successfully", updatedLanguageLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("05 Verify whether the validations during add language are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("05 Verify whether the validations during add language are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"English\"", "4", null, DisplayName="05 Verify whether the validations during add language are working as expected.(\"l" +
            "ija2512@gmail.com\",\"123456\",\"English\",4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Hindi\"", "5", null, DisplayName="05 Verify whether the validations during add language are working as expected.(\"l" +
            "ija2512@gmail.com\",\"123456\",\"Hindi\",5)")]
        public async global::System.Threading.Tasks.Task _05VerifyWhetherTheValidationsDuringAddLanguageAreWorkingAsExpected_(string email_Address, string password, string language, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Language", language);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("05 Verify whether the validations during add language are working as expected.", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
 await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
 await testRunner.AndAsync(string.Format("verify adding language {0} validations are working", language), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("06 Verify whether the validations during edit language are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("06 Verify whether the validations during edit language are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"English\"", "\"Native/Bilingual\"", "\"French\"", "\"Fluent\"", "6", null, DisplayName="06 Verify whether the validations during edit language are working as expected.(\"" +
            "lija2512@gmail.com\",\"123456\",\"English\",\"Native/Bilingual\",\"French\",\"Fluent\",6)")]
        public async global::System.Threading.Tasks.Task _06VerifyWhetherTheValidationsDuringEditLanguageAreWorkingAsExpected_(string email_Address, string password, string language1, string languageLevel1, string language2, string languageLevel2, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Language1", language1);
            argumentsOfScenario.Add("LanguageLevel1", languageLevel1);
            argumentsOfScenario.Add("Language2", language2);
            argumentsOfScenario.Add("LanguageLevel2", languageLevel2);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("06 Verify whether the validations during edit language are working as expected.", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language1, languageLevel1), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language2, languageLevel2), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync(string.Format("verify editing language {0} and {1} validations are working", language1, languageLevel1), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("07 Verify whether once all  the four languages added are displayed in the list th" +
            "e Add New button gets disabled")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("07 Verify whether once all  the four languages added are displayed in the list th" +
            "e Add New button gets disabled")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Java\"", "\"Basic\"", "\"Javascript\"", "\"Fluent\"", "\"C#\"", "\"Fluent\"", "\"Python\"", "\"Basic\"", "7", null, DisplayName="07 Verify whether once all  the four languages added are displayed in the list th" +
            "e Add New button gets disabled(\"lija2512@gmail.com\",\"123456\",\"Java\",\"Basic\",\"Jav" +
            "ascript\",\"Fluent\",\"C#\",\"Fluent\",\"Python\",\"Basic\",7)")]
        public async global::System.Threading.Tasks.Task _07VerifyWhetherOnceAllTheFourLanguagesAddedAreDisplayedInTheListTheAddNewButtonGetsDisabled(string email_Address, string password, string language, string languageLevel, string language1, string languageLevel1, string language2, string languageLevel2, string language3, string languageLevel3, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Language", language);
            argumentsOfScenario.Add("LanguageLevel", languageLevel);
            argumentsOfScenario.Add("Language1", language1);
            argumentsOfScenario.Add("LanguageLevel1", languageLevel1);
            argumentsOfScenario.Add("Language2", language2);
            argumentsOfScenario.Add("LanguageLevel2", languageLevel2);
            argumentsOfScenario.Add("Language3", language3);
            argumentsOfScenario.Add("LanguageLevel3", languageLevel3);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("07 Verify whether once all  the four languages added are displayed in the list th" +
                    "e Add New button gets disabled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
 await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language1, languageLevel1), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language2, languageLevel2), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language3, languageLevel3), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.WhenAsync(string.Format("the user clicks on Add New button and creates the last language record with {0} a" +
                            "nd {1} after that the button is disabled", language, languageLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("08 Verify whether the existing record is deleted on clicking the cross (X) icon a" +
            "nd a message is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("08 Verify whether the existing record is deleted on clicking the cross (X) icon a" +
            "nd a message is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Language")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"French\"", "\"Beginner\"", "\"French\"", "8", null, DisplayName="08 Verify whether the existing record is deleted on clicking the cross (X) icon a" +
            "nd a message is displayed(\"lija2512@gmail.com\",\"123456\",\"French\",\"Beginner\",\"Fre" +
            "nch\",8)")]
        public async global::System.Threading.Tasks.Task _08VerifyWhetherTheExistingRecordIsDeletedOnClickingTheCrossXIconAndAMessageIsDisplayed(string email_Address, string password, string language, string languageLevel, string language1, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Language", language);
            argumentsOfScenario.Add("LanguageLevel", languageLevel);
            argumentsOfScenario.Add("Language1", language1);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("08 Verify whether the existing record is deleted on clicking the cross (X) icon a" +
                    "nd a message is displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
 await testRunner.WhenAsync(string.Format("the user logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 93
 await testRunner.AndAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button", language, languageLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
 await testRunner.WhenAsync(string.Format("the user clicks on the cross icon against the {0} record", language1), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
 await testRunner.ThenAsync(string.Format("the {0} record should be deleted", language), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
