// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MarsProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class SkillsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Skills", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Skills.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Skills.feature.ndjson", 8);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("01 Verify whether user with valid credentials is redirected to Profile page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("01 Verify whether user with valid credentials is redirected to Profile page")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Skills")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SkillsTests")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Hi Lija\"", "0", null, DisplayName="01 Verify whether user with valid credentials is redirected to Profile page(\"lija" +
            "2512@gmail.com\",\"123456\",\"Hi Lija\",0)")]
        public async global::System.Threading.Tasks.Task _01VerifyWhetherUserWithValidCredentialsIsRedirectedToProfilePage(string email_Address, string password, string profile_Name, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SkillsTests"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Profile_Name", profile_Name);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01 Verify whether user with valid credentials is redirected to Profile page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.WhenAsync(string.Format("the user clicks logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.ThenAsync(string.Format("the user should be redirected to the Profile page with Profile name {0}", profile_Name), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 8
 await testRunner.AndAsync("click on Skill tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("02 Verify whether the user on clicking Add New button in Skills tab is able to cr" +
            "eate a record")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("02 Verify whether the user on clicking Add New button in Skills tab is able to cr" +
            "eate a record")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Skills")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Automated testing\"", "\"Expert\"", "1", null, DisplayName="02 Verify whether the user on clicking Add New button in Skills tab is able to cr" +
            "eate a record(\"lija2512@gmail.com\",\"123456\",\"Automated testing\",\"Expert\",1)")]
        public async global::System.Threading.Tasks.Task _02VerifyWhetherTheUserOnClickingAddNewButtonInSkillsTabIsAbleToCreateARecord(string email_Address, string password, string skill, string skillLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Skill", skill);
            argumentsOfScenario.Add("SkillLevel", skillLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02 Verify whether the user on clicking Add New button in Skills tab is able to cr" +
                    "eate a record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
   await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.WhenAsync(string.Format("the user clicks logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
 await testRunner.ThenAsync("click on Skill tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
 await testRunner.WhenAsync(string.Format("the user clicks on AddNew button enters {0} and {1} and clicks on Add button in t" +
                            "he skills section", skill, skillLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
 await testRunner.ThenAsync(string.Format("the {0} skill record should be displayed in the table", skill), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("03 Verify whether the user is able to update the skills record created")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("03 Verify whether the user is able to update the skills record created")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Skills")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Automated testing\"", "\"Intermediate\"", "2", null, DisplayName="03 Verify whether the user is able to update the skills record created(\"lija2512@" +
            "gmail.com\",\"123456\",\"Automated testing\",\"Intermediate\",2)")]
        public async global::System.Threading.Tasks.Task _03VerifyWhetherTheUserIsAbleToUpdateTheSkillsRecordCreated(string email_Address, string password, string skill, string updatedSkill_Level, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Skill", skill);
            argumentsOfScenario.Add("UpdatedSkill_Level", updatedSkill_Level);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03 Verify whether the user is able to update the skills record created", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
   await testRunner.WhenAsync(string.Format("the user clicks logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
 await testRunner.ThenAsync("click on Skill tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
 await testRunner.AndAsync(string.Format("the {0} skill record should be displayed in the table", skill), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.ThenAsync(string.Format("the user clicks on the edit icon and updates the skill level{0} and clicks on upd" +
                            "ate button", updatedSkill_Level), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
 await testRunner.AndAsync("the <UpdatedSkillLevel> skill level should get updated successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("04 Verify whether the validations during add skills are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("04 Verify whether the validations during add skills are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Skills")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Automated testing\"", "\"Intermediate\"", "3", null, DisplayName="04 Verify whether the validations during add skills are working as expected.(\"lij" +
            "a2512@gmail.com\",\"123456\",\"Automated testing\",\"Intermediate\",3)")]
        public async global::System.Threading.Tasks.Task _04VerifyWhetherTheValidationsDuringAddSkillsAreWorkingAsExpected_(string email_Address, string password, string existing_Skill, string existing_Skilllevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Existing_Skill", existing_Skill);
            argumentsOfScenario.Add("Existing_skilllevel", existing_Skilllevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04 Verify whether the validations during add skills are working as expected.", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
 await testRunner.WhenAsync(string.Format("the user clicks logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
 await testRunner.AndAsync("click on Skill tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync(string.Format("verify the Add skill validations and also when entering  {0} and {1} are working", existing_Skill, existing_Skilllevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("05 Verify whether the validations during edit skills are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("05 Verify whether the validations during edit skills are working as expected.")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Skills")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "4", null, DisplayName="05 Verify whether the validations during edit skills are working as expected.(\"li" +
            "ja2512@gmail.com\",\"123456\",4)")]
        public async global::System.Threading.Tasks.Task _05VerifyWhetherTheValidationsDuringEditSkillsAreWorkingAsExpected_(string email_Address, string password, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("05 Verify whether the validations during edit skills are working as expected.", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
 await testRunner.WhenAsync(string.Format("the user clicks logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
 await testRunner.AndAsync("click on Skill tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.AndAsync("verify the Edit skill validations are working", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("06 Verify whether the existing skill record is deleted on clicking the cross (X) " +
            "icon and a message is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("06 Verify whether the existing skill record is deleted on clicking the cross (X) " +
            "icon and a message is displayed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Skills")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("\"lija2512@gmail.com\"", "\"123456\"", "\"Automated testing\"", "5", null, DisplayName="06 Verify whether the existing skill record is deleted on clicking the cross (X) " +
            "icon and a message is displayed(\"lija2512@gmail.com\",\"123456\",\"Automated testing" +
            "\",5)")]
        public async global::System.Threading.Tasks.Task _06VerifyWhetherTheExistingSkillRecordIsDeletedOnClickingTheCrossXIconAndAMessageIsDisplayed(string email_Address, string password, string skill, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email_address", email_Address);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Skill", skill);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("06 Verify whether the existing skill record is deleted on clicking the cross (X) " +
                    "icon and a message is displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
 await testRunner.GivenAsync("the Mars Project url is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
 await testRunner.WhenAsync(string.Format("the user clicks logs in with valid credentials {0} and {1}", email_Address, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
 await testRunner.ThenAsync("the user should be redirected to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
 await testRunner.AndAsync("click on Skill tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.WhenAsync("the user clicks on the cross icon against the <skill> skill record", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
 await testRunner.ThenAsync(string.Format("the {0} skill record should be deleted", skill), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
